import Head from 'next/head'
import { Heading } from '@chakra-ui/react'

export default function Home(props) {
  console.log(props)
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading as="h3" size="sm">Hello world</Heading>
      </main>
    </>
  )
}

export async function getServerSideProps(context){
  const results = await fetch('https://fakestoreapi.com/products')
  .then(res=>res.json())
  
  return {
    props: {
      results
    }
  }
}
