import Head from 'next/head'
import { GetServerSideProps } from 'next'

import { Header } from '@/components/Header'
import { TopBar } from '@/components/TopBar'
import { HomeCategories } from '@/components/HomeCategories'
import { AdvantageSection } from '@/components/AdvantageSection'

import { Categories } from '@/models/Categories'

import { Box, Container, Flex, Grid, SimpleGrid, Text } from '@chakra-ui/react'
import { ProductCard } from '@/components/ProductCard'

export type Product = {
  id: number,
  title: string,
  price: number,
  description: string,
  category: string,
  image: string,
  rating: {
    count: number,
    rate: number, 
  }
}


type Props ={
  products: Product[],
  categories: Categories[]
}

export default function Home({products, categories}: Props) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <TopBar />
        <Box marginBottom="2rem">
          <Header />
        </Box>  
      <main>
        <Container size={{
          lg:'lg',
        }}>
          <HomeCategories categories={categories}/>

          <AdvantageSection/>

        </Container>  

        <Container maxW={{
          base: '100%',
          md: '1110px'
        }}>
          <Grid 
              overflowX='scroll'
              gridTemplateColumns={{
                base: 'repeat(auto-fit, 255px)',
                md: 'repeat(auto-fill, minmax(255px, 1fr))' 
              }}
              gridAutoColumns='255px'
              gridAutoRows='1fr'
              gridAutoFlow={{
                base: 'column',
                md: 'row'
              }}
              gap='1.85rem'
              scrollSnapType='x mandatory'
              alignItems='stretch'
            >
            {products.map((product,i) => {
              return <Box 
                        marginLeft={{
                          base: i === 0? '1rem' : '0',
                          md: '0'
                        }}
                        key={product.id} 
                        scrollSnapAlign='center' 
                        border='solid 1px' 
                        borderColor='gray.200' 
                        padding='1rem'
                      >
                      <ProductCard {...product}/>
                     </Box>
            })}
          </Grid> 
        </Container>
        
      </main>
    </>
  )
}

//Server side
export async function getServerSideProps(context: GetServerSideProps){
  const products = await fetch("https://fakestoreapi.com/products")
    .then(res => res.json())
  const categories = await fetch("https://fakestoreapi.com/products/categories")
    .then(res => res.json())


  return {
    props: {
      products,
      categories
    }
  }
}
